name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'
  schedule:
    #- cron: '0 6,18 * * *'
    - cron: '0 0,3,6,9,12,15,18,21 * * *'
  workflow_dispatch:

jobs:
  test-job:
    name: CI
    runs-on: macos-11.0
    timeout-minutes: 90
    environment: Signing

    strategy:
      matrix:
        repo: [Av8]


    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: "Import Certificate: Development"
        uses: devbotsxyz/xcode-import-certificate@master
        with:
          certificate-data: ${{ secrets.DEVELOPMENT_CERTIFICATE_DATA }}
          certificate-passphrase: ${{ secrets.DEVELOPMENT_CERTIFICATE_PASSPHRASE }}
          keychain-password: ${{ secrets.KEYCHAIN_PASSWORD }}

      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
          submodules: recursive
          repository: glimpseio/InformaTiq
          token: ${{ secrets.CI_ACCESS_TOKEN }}

      #- name: Show Simulators
      #  run: |
      #  xcrun simctl list

      - name: Test Framework
        run: |
          xcodebuild build \
            -scheme "${{ matrix.repo }}Werk" \
            -configuration Debug \
            ONLY_ACTIVE_ARCH=YES CODE_SIGNING_REQUIRED=NO \
            | xcpretty --report html --screenshots && exit ${PIPESTATUS[0]}

      #- name: Build watchOS
        #run: |
        #  xcodebuild build \
        #    -scheme "${{ matrix.repo }}App" \
        #    -configuration Release \
        #    -sdk "watchsimulator7.2" \
        #    -destination "OS=7.2,name=Apple Watch Series 6 - 44mm" \
        #    ONLY_ACTIVE_ARCH=YES CODE_SIGNING_REQUIRED=NO \
        #    | xcpretty --report html --screenshots && exit ${PIPESTATUS[0]}

      #- name: Test tvOS
        #run: |
        #  xcodebuild build \
        #    -scheme "${{ matrix.repo }}App" \
        #    -configuration Release \
        #    -sdk "appletvsimulator14.3" \
        #    -destination "OS=14.3,name=Apple TV" \
        #    ONLY_ACTIVE_ARCH=YES CODE_SIGNING_REQUIRED=NO \
        #    | xcpretty --report html --screenshots && exit ${PIPESTATUS[0]}

      - name: Test macOS
        run: |
          xcodebuild build \
            -scheme "${{ matrix.repo }}Mac" \
            -configuration Release \
            ONLY_ACTIVE_ARCH=YES CODE_SIGNING_REQUIRED=NO \
            | xcpretty --report html --screenshots && exit ${PIPESTATUS[0]}

      - name: Test iPhoneOS
        run: |
          xcodebuild build \
            -scheme "${{ matrix.repo }}App" \
            -configuration Release \
            -sdk "iphonesimulator14.4" \
            -destination "OS=14.4,name=iPhone 12 Mini" \
            ONLY_ACTIVE_ARCH=YES CODE_SIGNING_REQUIRED=NO \
            | xcpretty --report html --screenshots && exit ${PIPESTATUS[0]}

      - name: Test iPadOS
        run: |
          xcodebuild build \
            -scheme "${{ matrix.repo }}App" \
            -configuration Release \
            -sdk "iphonesimulator14.4" \
            -destination "OS=14.4,name=iPhone 12 Mini" \
            ONLY_ACTIVE_ARCH=YES CODE_SIGNING_REQUIRED=NO \
            | xcpretty --report html --screenshots && exit ${PIPESTATUS[0]}


